common:
  exp_name: ScanObjectNN_PRANet0710_2
  init: True
  model: PRANet
  seed: 1
  dataset: ScanObjectNN

  smoothing: True
  epochs: 250

  # ISL
  k_hat: 20

  # IRL
  m_list: [0,4,4,4]
  sample_ratio_list: [0, 4, 8, 16]
  
  start_layer: 1
  

  # FC
  dropout: 0.5
  emb_dims: 1024

  # train
  workers: 4
  num_points: 1024
  num_classes: 15
  batch_size: 32

  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9

  checkpoint:
  data_root: "./data/h5_files"


